### PR TITLE
Add pcengines target

### PR DESCRIPTION
**Pull request by macpijan**
This is a WIP status MR to provoke a discussion on adding new supported boards. I'm trying to add the x86 PC Engines APU2 target: https://www.pcengines.ch/apu2.htm

Major build issues at the moment:

1. Application server build failing:

```
| mkdir -p build
| go build  -ldflags "-s -w -X main.version=3.10.0" -o build/chirpstack-application-server cmd/chirpstack-application-server/main.go
| # github.com/tmc/grpc-websocket-proxy/wsproxy
| build/pkg/mod/github.com/brocaar/grpc-websocket-proxy@v1.0.0/wsproxy/websocket_proxy.go:172:18: undefined: http.NewRequestWithContext
| make: *** [Makefile:8: build] Error 2
| WARNING: exit code 1 from a shell command.
| 
ERROR: Task (/chirpstack-gateway-os/layers/chirpstack/meta-chirpstack/recipes-chirpstack/chirpstack-application-server/chirpstack-application-server_3.10.0.bb:do_compile) failed with exit code '1'
```

Reason: go must be at least v1.13 (1.12.9 in current build)
Source: https://github.com/ysmood/kit/issues/1
Resolution: update layers to Dunfell (go is in 1.14 here)

2. concetratord build fails when target machine is the same arch as build machine
ld cannot find binaries, because the native linker wrapper is used.
This is likely a bug in meta-rust-bin: https://github.com/rust-embedded/meta-rust-bin/issues/70
Local workaround applied for a moment to always use the target linker wrapper.

### CODE REVIEW

**Comment by macpijan** [comment]
It may make sense to split it into several problems
- update to Dunfell and build/test RPI images
- build golang recipes inside Yocto and test such images on RPI - so boards with other architectures can be properly supported
- after the above passes, discuss / add target for another board

**Comment by macpijan** [comment]
This PR already contains changes from https://github.com/brocaar/chirpstack-gateway-os/pull/55

Image built boots on the APU2 board:

```
ChirpStack Gateway OS 3.3.0-test.6 pcengines-apu2 /dev/ttyS0

pcengines-apu2 login: admin
Password: 
   ________    _           _____ __             __     _     
  / ____/ /_  (_)________ / ___// /_____ ______/ /__  (_)___ 
 / /   / __ \/ / ___/ __ \\__ \/ __/ __ `/ ___/ //_/ / / __ \
/ /___/ / / / / /  / /_/ /__/ / /_/ /_/ / /__/ ,< _ / / /_/ /
\____/_/ /_/_/_/  / .___/____/\__/\__,_/\___/_/|_(_)_/\____/ 
                 /_/

Documentation and copyright information:
> www.chirpstack.io

Commands:
> sudo gateway-config  - configure the gateway
> sudo monit summary   - display service monitor

   ________    _           _____ __             __     _     
  / ____/ /_  (_)________ / ___// /_____ ______/ /__  (_)___ 
 / /   / __ \/ / ___/ __ \\__ \/ __/ __ `/ ___/ //_/ / / __ \
/ /___/ / / / / /  / /_/ /__/ / /_/ /_/ / /__/ ,< _ / / /_/ /
\____/_/ /_/_/_/  / .___/____/\__/\__,_/\___/_/|_(_)_/\____/ 
                 /_/

Documentation and copyright information:
> www.chirpstack.io

Commands:
> sudo gateway-config  - configure the gateway
> sudo monit summary   - display service monitor

pcengines-apu2:~$ sudo monit summary                                                                                                                                                                               
Password: 
Monit 5.26.0 uptime: 0m
 Service Name                     Status                      Type          
 pcengines-apu2                   OK                          System        
 chirpstack-network-server        OK                          Process       
 chirpstack-gateway-bridge        OK                          Process       
 chirpstack-concentratord         Initializing                Process       
 chirpstack-application-server    Does not exist              Process      
```

**Comment by macpijan** [comment]
Some more notes on this:

The `concentratord` will likely not work on this board currently, as it expects to use the `spidev` https://github.com/brocaar/chirpstack-concentratord/blob/master/libloragw-sx1301/src/spi.rs#L6 ?

The board uses libmpsse library for SPI: https://github.com/lpn-plant/libmpsse

In order to make it work with `concentratord`, I guess the HAL for mpsse SPI - such as this one:
https://github.com/lpn-plant/lora_gateway/blob/lpnGate/libloragw/src/loragw_spi.mpsse.c
would need to be implemented in the concetratord?

Currently, we are trying out the rest of the stack with the `packet forwarder` instead of the `concetratord`.

**Comment by brocaar** [comment]
@macpijan Concentratord uses the same HAL as the Semtech UDP Packet Forwarder, so it would be surprised if it would work on one, but not on the other.

Please note that the Rust code to which you are linking does nothing more than changing the spi device, which only changes the string. The actual SPI code is in:

https://github.com/Lora-net/lora_gateway/blob/master/libloragw/src/loragw_spi.native.c#L32

---

If supporting the pcengines target would mean that the Semtech HAL can't be used anymore (or it would require an additional Concentratord implementation), then this is an issue as it brings a lot of additional maintenance work.

Is my assumption correct that the mpsse library "tunnels" SPI over FTDI (thus USB interface)?

**Comment by macpijan** [comment]
> mpsse library "tunnels" SPI over FTDI (thus USB interface)

This is my understanding of this as well, although I have not coded this part - merely integrated it. Currently, we use the `lora_pkt_fwd` instead of the  `concetratord` as there was no resources at this point to look into it and the packet forwarded **just works** with the rest of the Chirpstack stack. Moreover, we like the approach of using Docker containers with Chirpstack components on the APU2, so the chirsptack-gateway-os is not that necessary anymore. I doubt this MR will receive more attention from our side in near future. At least we have updated the Yocto relase and improved some recipes as part of it :)

**Pull request closed without merging**
